# Generated by Django 5.0.7 on 2025-03-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('student', 'student'), ('admin', 'admin')], default='student', max_length=10)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=50)),
                ('roll', models.CharField(blank=True, max_length=8, null=True)),
                ('registration', models.CharField(blank=True, max_length=12, null=True)),
                ('session', models.CharField(blank=True, max_length=4, null=True)),
                ('address', models.CharField(max_length=100)),
                ('nationality_type', models.CharField(max_length=10)),
                ('nationality_number', models.CharField(max_length=17)),
            ],
        ),
    ]
