# Generated by Django 5.0.7 on 2025-05-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_email_alter_profile_nationality_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
