# Generated by Django 5.0.7 on 2025-05-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blood',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality_type',
            field=models.CharField(choices=[('BIRTH', 'BIRTH'), ('NID', 'NID')], max_length=10),
        ),
    ]
