# Generated by Django 5.0.7 on 2025-05-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_blood_alter_profile_nationality_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True),
        ),
    ]
