# Generated by Django 5.0.7 on 2025-05-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_blood'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
