# Generated by Django 5.0.7 on 2025-05-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='test',
        ),
    ]
