# Generated by Django 5.0.7 on 2025-05-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.IntegerField(blank=True, choices=[(3, 3), (7, 7), (10, 10), (15, 15), (30, 30)], default=7, null=True),
        ),
    ]
