# Generated by Django 5.0.7 on 2025-05-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='borrow_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('borrowed', 'borrowed'), ('returned', 'returned'), ('overdue', 'overdue')], default='pending', max_length=12),
        ),
    ]
