# Generated by Django 5.0.7 on 2025-06-02 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_image'),
        ('books', '0001_initial'),
        ('transactions', '0005_remove_transaction_user_transaction_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_transactions', to='books.book'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_transactions', to='accounts.profile'),
        ),
    ]
